### ISSUE TITLE
"ReferenceError: window is not defined" when loading i18next-xhr-backend

### ISSUE THREAD

**Issue by TitaneBoy** [i18next/i18next-xhr-backend#88]
Hi. I think I have an issue when using i18next-xhr-backend.

I get an error when I try to use this module.

This is what I wrote in server-side:

```
var i18next = require('i18next');
var i18nextMiddleware = require('i18next-express-middleware');
var i18nextBackend = require('i18next-node-fs-backend');
var i18nextXHR = require('i18next-xhr-backend');
var i18nextOptions = {debug:true, preload: ['es','fr', 'en-US'], fallbackLng:'en-US', whitelist:['fr','en-US', 'es'],  saveMissingTo:'all', saveMissing:true, ns:'Web_Server', defaultNS:'Web_Server', backend:{loadPath: 'language/static/{{lng}}/{{ns}}.json', addPath: 'language/static/{{lng}}/{{ns}}.missing.json', jsonIndent: 2}};

var port = 80;
var app = express();

i18next
  .use(i18nextMiddleware.LanguageDetector)
  .use(i18nextBackend)
  .use(i18nextXHR)
  .init(i18nextOptions);
```

Am I doing something wrong ?

The following is the errors I got in the console log:

```
C:\Personal_Data\Demo_Setup\Node.js\Express\DemoApp>node server.js
Local strategy used
i18next::languageUtils: rejecting non-whitelisted language code: en
C:\Personal_Data\Demo_Setup\Node.js\Express\DemoApp\node_modules\i18next-xhr-backend\dist\commonjs\index.js:43
    window.console && console.log(e);
    ^

ReferenceError: window is not defined
    at Object.ajax (C:\Personal_Data\Demo_Setup\Node.js\Express\DemoApp\node_modules\i18next-xhr-backend\dist\commonjs\index.js:43:5)
    at Backend.loadUrl (C:\Personal_Data\Demo_Setup\Node.js\Express\DemoApp\node_modules\i18next-xhr-backend\dist\commonjs\index.js:127:20)
    at Backend.read (C:\Personal_Data\Demo_Setup\Node.js\Express\DemoApp\node_modules\i18next-xhr-backend\dist\commonjs\index.js:120:12)
    at Connector.read (C:\Personal_Data\Demo_Setup\Node.js\Express\DemoApp\node_modules\i18next\dist\commonjs\BackendConnector.js:166:25)
    at Connector.read (C:\Personal_Data\Demo_Setup\Node.js\Express\DemoApp\node_modules\i18next\dist\commonjs\BackendConnector.js:236:18)
    at C:\Personal_Data\Demo_Setup\Node.js\Express\DemoApp\node_modules\i18next\dist\commonjs\BackendConnector.js:247:18
    at Array.forEach (native)
    at C:\Personal_Data\Demo_Setup\Node.js\Express\DemoApp\node_modules\i18next\dist\commonjs\BackendConnector.js:246:25
    at Connector.load (C:\Personal_Data\Demo_Setup\Node.js\Express\DemoApp\node_modules\i18next\dist\commonjs\BackendConnector.js:249:11)
    at C:\Personal_Data\Demo_Setup\Node.js\Express\DemoApp\node_modules\i18next\dist\commonjs\i18next.js:224:44
    at Connector.load (C:\Personal_Data\Demo_Setup\Node.js\Express\DemoApp\node_modules\i18next\dist\commonjs\CacheConnector.js:56:41)
    at C:\Personal_Data\Demo_Setup\Node.js\Express\DemoApp\node_modules\i18next\dist\commonjs\i18next.js:223:40
    at I18n.loadResources (C:\Personal_Data\Demo_Setup\Node.js\Express\DemoApp\node_modules\i18next\dist\commonjs\i18next.js:226:8)
    at I18n.changeLanguage (C:\Personal_Data\Demo_Setup\Node.js\Express\DemoApp\node_modules\i18next\dist\commonjs\i18next.js:287:10)
    at I18n.init (C:\Personal_Data\Demo_Setup\Node.js\Express\DemoApp\node_modules\i18next\dist\commonjs\i18next.js:185:10)
    at Object.<anonymous> (C:\Personal_Data\Demo_Setup\Node.js\Express\DemoApp\server.js:23:4)
```

Thank you for your help.

**Comment by jamuhl** [comment]
i18next-xhr-backend is only for browsers using xhr.

for node there is remote, db or fs backends:
http://i18next.com/docs/ecosystem/#backends

where remote is basically what xhr is on browser (using request module to load resources from some server)

**Comment by TitaneBoy** [comment]
Thank you for your answer. I thought I must use this module to be able to load resources in the client-side.

**Comment by jamuhl** [comment]
on clientside yes. but the error you show is on server.

**Comment by Frikki** [comment]
Since it’s browser only, why do you check for `window.console` and not just `console`? @jamuhl 

Then we wouldn’t get the error.

**Comment by jamuhl** [comment]
You would not get an error...but still xhr backend would not work on nodejs.

But agree...nothing against removing that `window.`

**Comment by Frikki** [comment]
> ... still xhr backend would not work on nodejs

Correct, but for people who write tests, which are run with, for example, both mocha and karma, for software that can be configured to be used either in the browser or on node.js, which may use i18next-xhr-backend, it would eliminate the error. However, the tests could also be written differently.

**Comment by jamuhl** [comment]
tests should not test sideeffects of using i18n frameworks - you should test your components - which leads to use a mock for i18next.t.

but as you see my last commit i removed the window https://github.com/i18next/i18next-xhr-backend/commit/c8cc0a125b9d6fdce941f87f73f1f626b8363366 - this change will be published with the next version - or if you need that urgent i can publish a new version on npm later today.
